---
# =============================================================================
# Ansible Role: Tailscale - Molecule Convergence (Uninstall Scenario)
# =============================================================================

- name: Molecule | Converge (uninstall)
  hosts: all

  pre_tasks:
    - name: 🔄 Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: >
        ansible_os_family == "Debian"

  vars:
    tailscale_auth_key: ""
    tailscale_track: "stable"
    tailscale_validate_connectivity: false

  tasks:
    - name: 🧩 Install role first to ensure resources exist
      ansible.builtin.include_role:
        name: ../../..

    - name: 🧹 Run role in absent state
      ansible.builtin.include_role:
        name: ../../..
      vars:
        tailscale_state: absent


