---
# Tailscale Molecule — Converge for uninstall scenario.

- name: Molecule | Converge (uninstall)
  hosts: all

  pre_tasks:
    - name: Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when:
        - ansible_facts['os_family'] == "Debian"

  vars:
    tailscale_auth_key: ""
    tailscale_track: "stable"
    tailscale_validate_connectivity: false

  tasks:
    - name: Converge | Install role first to ensure resources exist
      ansible.builtin.include_role:
        name: ../../..

    - name: Converge | Run role in absent state
      ansible.builtin.include_role:
        name: ../../..
      vars:
        tailscale_state: absent
