---
# =============================================================================
# Ansible Role: Tailscale - Tasks: Repository
# =============================================================================
# OS-family dispatcher for package repository configuration.
# =============================================================================

- name: Tailscale | repository | Configure Debian-family repositories
  ansible.builtin.include_tasks: repository_debian.yml
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Tailscale | repository | Configure RedHat-family repositories
  ansible.builtin.include_tasks: repository_redhat.yml
  when:
    - ansible_facts['os_family'] == 'RedHat'
