---
# Tailscale Handlers — Service management operations triggered by tasks.

- name: Tailscale | handlers | Restart Tailscale service
  become: true
  ansible.builtin.service:
    name: "{{ __tailscale_service_name }}"
    state: restarted

- name: Tailscale | handlers | Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - ansible_facts['service_mgr'] == 'systemd'

- name: Tailscale | handlers | Restart rsyslog
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: restarted
