---
# =============================================================================
# Ansible Role: Tailscale - Molecule Preparation Playbook
# =============================================================================

- name: Molecule | Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: 🛠️ Prepare | Fix /etc/shadow permissions
      register: etc_shadow
      ansible.builtin.shell:
        cmd: |
          echo "🔍 Checking /etc/shadow permissions..."
          ls -l /etc/shadow
          chmod 0400 /etc/shadow
          echo "✅ Fixed /etc/shadow permissions:"
          ls -l /etc/shadow
      changed_when: true

    - name: 📊 Prepare | Verify shadow file permissions
      ansible.builtin.debug:
        var: etc_shadow.stdout

    - name: 🔧 Prepare | Ensure required directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - /usr/share/keyrings
        - /etc/apt/sources.list.d
      when: >
        ansible_os_family == "Debian"

    - name: 🔄 Prepare | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: >
        ansible_os_family == "Debian"

    - name: ⏳ Prepare | Wait for systemd to complete initialization
      ansible.builtin.systemd:
        name: multi-user.target
        state: started
      register: systemctl_status
      until: true
      retries: 30
      delay: 5
      when: >
        ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: false

    - name: 🛠️ Prepare | Create test log directory
      ansible.builtin.file:
        path: /var/log/tailscale-test
        state: directory
        mode: '0755'
        owner: root
        group: root
