---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: logging-instance
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: ${MOLECULE_PLAYBOOK:-verify.yml}
    prepare: ${MOLECULE_PLAYBOOK:-prepare.yml}
  lint:
    name: ansible-lint
  config_options:
    defaults:
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "true"
  inventory:
    group_vars:
      all:
        tailscale_auth_key: ""
        tailscale_enable_logging: true
        tailscale_validate_connectivity: false
        tailscale_track: "stable"

verifier:
  name: ansible
  options:
    verbose: true


