---
# Tailscale Molecule — Prepare target for logging scenario.

- name: Molecule | Prepare (logging)
  hosts: all
  gather_facts: true

  tasks:
    - name: Prepare | Fix /etc/shadow permissions
      ansible.builtin.file:
        path: /etc/shadow
        mode: '0400'

    - name: Prepare | Ensure required directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - /usr/share/keyrings
        - /etc/apt/sources.list.d
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: Prepare | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: Prepare | Wait for systemd to complete initialization
      ansible.builtin.systemd:
        name: multi-user.target
        state: started
      register: systemctl_status
      until: true
      retries: 30
      delay: 5
      when:
        - ansible_facts['service_mgr'] == 'systemd'
      changed_when: false
      failed_when: false
