---
# Tailscale Molecule — Verify logging scenario results.

- name: Molecule | Verify (logging)
  hosts: all
  gather_facts: true

  tasks:
    - name: Verify | Check rsyslog config file exists
      ansible.builtin.stat:
        path: "/etc/rsyslog.d/49-tailscale.conf"
      register: __verify_rsyslog

    - name: Verify | Assert rsyslog config present
      ansible.builtin.assert:
        that:
          - __verify_rsyslog['stat']['exists']
        fail_msg: "RSyslog configuration for Tailscale not found"
        success_msg: "RSyslog configuration present"

    - name: Verify | Check systemd override exists
      ansible.builtin.stat:
        path: "/etc/systemd/system/tailscaled.service.d/logging.conf"
      register: __verify_override
      when:
        - ansible_facts['service_mgr'] == 'systemd'

    - name: Verify | Assert systemd override present
      ansible.builtin.assert:
        that:
          - __verify_override['stat']['exists']
        fail_msg: "Systemd logging override not found"
        success_msg: "Systemd logging override present"
      when:
        - ansible_facts['service_mgr'] == 'systemd'

    - name: Verify | Check logrotate config exists
      ansible.builtin.stat:
        path: "/etc/logrotate.d/tailscale"
      register: __verify_logrotate

    - name: Verify | Assert logrotate present
      ansible.builtin.assert:
        that:
          - __verify_logrotate['stat']['exists']
        fail_msg: "Logrotate configuration for Tailscale not found"
        success_msg: "Logrotate configuration present"
